ch=input("donner la chaine ")
print("le nombre de caractere est :",len(ch))
print("le nombre d'occurence est :",ch.count("o"))
print("la nombre des mots est :",ch.split(" "))
print("la nombre des mots est :",len(ch.split(" ")))
l=ch.split()
print("l'ordre des mots inverse est :",l[::-1])
print(" ".join(l[::-1]))
print(ch.replace("bonjour","bienvennus"))
